[target.x86_64-apple-darwin]
linker = "x86_64-apple-darwin14-clang"
ar = "x86_64-apple-darwin14-ar"
rustflags = ["-lz", "-lbz2", "-llzma", "-l", "framework=WebKit", "-C", "link-args=-framework AudioUnit"]